name: Git tags
run-name: "Publishing git tag for pull request #${{ github.event.number }}"

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs: 
  create-tag:
    uses: Lattice-Trade/membrane-public-github-actions/.github/workflows/gh-publish-release-sdk.v1.yml@main
    with:
      WORKING_DIR: .
    secrets: inherit